apiVersion: v1
kind: Service
metadata:
  name: {{.Values.AuthService.DNS}}
spec:
  selector:
    app: {{.Values.AuthService.DNS}}
  ports:
    - protocol: TCP
      port: {{.Values.AuthService.RestPort}}
      targetPort: {{.Values.All.targetPort}}
      name: http
  type: LoadBalancer
  