apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.Gateway.DNS}}
  labels:
    app: {{.Values.Gateway.DNS}}
spec:
  replicas: {{.Values.Gateway.DeploymentReplicas}}
  selector:
    matchLabels:
      app: {{.Values.Gateway.DNS}}
  template:
    metadata:
      labels:
        app: {{.Values.Gateway.DNS}}
    spec:
      containers:
        - name: gateway
          image:  "{{.Values.Gateway.Image}}:{{.Values.Tag}}"
          imagePullPolicy: {{.Values.Policy.ImagePullPolicy}}
          ports:
            - containerPort: {{.Values.Gateway.RestPort}}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          env:
            - name: GOGC
              value: "100"
            - name: GODEBUG
              value: "madvdontneed=1"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            tcpSocket:
              port: {{.Values.All.targetPort}}
            failureThreshold: 30
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: {{.Values.All.targetPort}}
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: {{.Values.All.targetPort}}
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 2

      restartPolicy: {{.Values.Policy.RestartPolicy}}
      securityContext:
        runAsNonRoot: false


