apiVersion: v1
kind: ServiceAccount
metadata:
  name: setting-service-sa
  namespace: {{ .Values.TLS.Cert.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: setting-service-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: setting-service-sa
    namespace: {{ .Values.TLS.Cert.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io












