apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.SettingService.DNS }}
  namespace: {{ .Values.TLS.Cert.Namespace }}
spec:
  selector:
    app: {{.Values.SettingService.DNS}}
  ports:
    - protocol: TCP
      port: {{ .Values.SettingService.RestPort }}
      targetPort: {{ .Values.All.targetPort }}












