apiVersion: v1
kind: ServiceAccount
metadata:
  name: sysinfo-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sysinfo-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["clickhouse.altinity.com"]
    resources: ["clickhouseinstallations"]
    verbs: ["get", "list", "watch", "update", "patch"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sysinfo-binding
subjects:
  - kind: ServiceAccount
    name: sysinfo-sa
    namespace: midas
roleRef:
  kind: ClusterRole
  name: sysinfo-role
  apiGroup: rbac.authorization.k8s.io