apiVersion: v1
kind: Service
metadata:
  name: {{.Values.Frontend.DNS}}
spec:
  selector:
    app: {{.Values.Frontend.DNS}}
  ports:
    - protocol: TCP
      port: {{.Values.Frontend.RestPort}}
      targetPort: {{.Values.Frontend.RestPort}}
      nodePort: {{.Values.Frontend.NodePort}}
  type: LoadBalancer
