apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{.Values.EventService.DNS}}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.EventService.DNS}}
  updatePolicy:
    updateMode: "Recreate"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources:
          - memory
        controlledValues: RequestsAndLimits
        minAllowed:
          memory: "128Mi"
        maxAllowed:
          memory: "2Gi"
