apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.AgentScalerService.DNS }}-sa
  labels:
    app: {{ .Values.AgentScalerService.DNS }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.AgentScalerService.DNS }}-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update", "patch"]
  - apiGroups: ["clickhouse.altinity.com"]
    resources: ["clickhouseinstallations"]
    verbs: ["get", "list", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.AgentScalerService.DNS }}-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.AgentScalerService.DNS }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.AgentScalerService.DNS }}-role
  apiGroup: rbac.authorization.k8s.io












